Repository NREL/resstock, pull requests merged in 2024-07, with the labels that each got.

#1270 Map mobile homes to HPXML's "manufactured home"
  docs/read_the_docs/source/workflow_inputs/characteristics.rst
  measures/ResStockArguments/measure.rb
  measures/ResStockArguments/measure.xml
  resources/options_lookup.tsv
Labels: enhancement

#1269 ResStockArguments: convert args to double, integer
  .github/workflows/config.yml
  Rakefile
  docs/read_the_docs/source/changelog/changelog_dev.rst
  docs/read_the_docs/source/workflow_inputs/characteristics.rst
  docs/read_the_docs/source/workflow_inputs/create_characteristics_rst.rb
  measures/ResStockArguments/measure.rb
  measures/ResStockArguments/measure.xml
  measures/ResStockArguments/tests/resstock_arguments_test.rb
Labels: bug

#1253 Convert UpgradeCosts measure to ModelMeasure
  .github/workflows/config.yml
  docs/read_the_docs/source/basic_tutorial/architecture.rst
  docs/read_the_docs/source/changelog/changelog_dev.rst
  measures/BuildExistingModel/measure.rb
  measures/BuildExistingModel/measure.xml
  measures/ReportHPXMLOutput/README.md
  measures/ReportHPXMLOutput/README.md.erb
  measures/ReportHPXMLOutput/measure.rb
  measures/ReportHPXMLOutput/measure.xml
  measures/ResStockArguments/measure.rb
  measures/ResStockArguments/measure.xml
  measures/ResStockArguments/resources/constants.rb
  measures/UpgradeCosts/measure.rb
  measures/UpgradeCosts/measure.xml
  measures/UpgradeCosts/resources/constants.rb
  measures/UpgradeCosts/tests/upgrade_costs_test.rb
  project_national/national_baseline.yml
  project_national/national_upgrades.yml
  project_testing/testing_baseline.yml
  project_testing/testing_upgrades.yml
  resources/buildstock.rb
  test/analysis.rb
  test/base_results/baseline/annual/results_output.csv
  test/test_bsb_analysis.rb
  test/test_run_analysis.rb
  workflow/run_analysis.rb
Labels: bug, enhancement

#1277 ServerDirectoryCleanup: catch *schedules.csv, refactor
  docs/read_the_docs/source/basic_tutorial/architecture.rst
  docs/read_the_docs/source/changelog/changelog_dev.rst
  measures/ServerDirectoryCleanup/README.md
  measures/ServerDirectoryCleanup/measure.rb
  measures/ServerDirectoryCleanup/measure.xml
  project_national/national_baseline.yml
  project_national/national_upgrades.yml
Labels: bug
